# Note this file is not yet being used.

[General]
timerestriction: False
debug_mode: False
log_directory: ./logs

[EmailSettings]
# emailtype: "Gmail"
emailtype: Console

[SMSSettings]
# outboundsmstype = "WebService"
outboundsmstype: Console

[Twilio]
account_sid: AC9928868755ae47465138d2bd99c98b1b
auth_token: d01b75deef25037b870f1d00cb731b86

[AHC]
spsms_basic_auth: Basic QXNoZm9yZENhcnM6Q2FybGtqc2QwOTQ=
spsms_host: spremote.staffplan.co.uk
spsms_url: /AdvLearning/rest/SMSSubmissions.ashx

[Postgres]
pg_host: localhost
pg_dbname: blockbuster
pg_user: blockbuster
pg_passwd: blockbuster

[Pushover]
pushover_app_token: aR1kbXMA6Hw6peNxDiNEuQ5PgMPz7u

[Email]
smtp_server: smtp.gmail.com:587
mail_host: smtp.gmail.com
mail_port: 587
mail_username: blockbuster.notify@gmail.com
mail_fromaddr: blockbuster.notify@gmail.com
mail_password: 4S37R3FuEL8Sx0
mail_monitoring_addr: mattstibbs@gmail.com

[EmailTest]
fromaddr: blockbuster.notify@gmail.com
toaddr: matthew.stibbs@advancedcomputersoftware.com
subject: BlockBuster Notification: Please Move Your Car
message: Please could you move your car for Joe Bloggs.

[Numbers]
return_number: +447903516953
