language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database blockbuster;' -U postgres
script: nosetests --verbosity=3
branches:
  only:
    - develop
    - master
